FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    apt-utils \
    curl \
    git \
    iputils-ping \
    rsync \
    software-properties-common \
    unzip \
    vim \
    wget \
    zip
